name: preview-build

on:
  push:
    branches:
      - develop
      - hotfix/**
    paths:
      - app.json
      - eas.json
      - package.json
      - assets/app-icons/**

jobs:
  # 1️⃣ Read app version
  read_app_version:
    name: read-app-version
    type: custom
    steps:
      - uses: eas/checkout
      - id: outputs
        run: |
          VER=$(node -p "require('./package.json').version")
          echo "app_version=$VER" >> "$EAS_OUTPUT"
    outputs:
      app_version: ${{ steps.outputs.outputs.app_version }}

  # 2️⃣ Check for existing Android build
  get_android_build:
    name: check-android-build
    needs: [read_app_version]
    type: get-build
    params:
      platform: android
      runtime_version: ${{ needs.read_app_version.outputs.app_version }}
      app_version: ${{ needs.read_app_version.outputs.app_version }}

  # 3️⃣ Build Android (preview) if missing
  build_android:
    name: build-android-preview
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: preview

  # 4️⃣ Check for existing iOS build
  get_ios_build:
    name: check-ios-build
    needs: [read_app_version]
    type: get-build
    params:
      platform: ios
      runtime_version: ${{ needs.read_app_version.outputs.app_version }}
      app_version: ${{ needs.read_app_version.outputs.app_version }}

  # 5️⃣ Build iOS (preview) if missing
  build_ios:
    name: build-ios-preview
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: preview
