name: Preview OTA Update

on:
  push:
    branches:
      - develop
      - staging
      - feature/**
      - bugfix/**
    paths:
      - src/**
      - assets/**
      - index.js

jobs:
  # 1. Read App Version
  read_app_version:
    name: Read app version
    type: custom
    steps:
      - uses: eas/checkout
      - id: read
        run: |
          VER=$(node -p "require('./package.json').version")
          echo "app_version=$VER" >> "$EAS_OUTPUT"
    outputs:
      app_version: ${{ steps.read.outputs.app_version }}

  # 2. Check if a compatible Android build exists
  get_android_build:
    name: Check Android Build
    needs: [read_app_version]
    type: get-build
    params:
      platform: android
      profile: preview
      runtime_version: ${{ needs.read_app_version.outputs.app_version }}
      app_version: ${{ needs.read_app_version.outputs.app_version }}

  # 3. Publish OTA update if build exists
  update_android:
    name: Publish Android OTA update
    needs: [get_android_build]
    if: ${{ needs.get_android_build.outputs.build_id }}
    type: update
    params:
      platform: android
      branch: preview
      message: "OTA update for version ${{ needs.read_app_version.outputs.app_version }}"

  # 4. Check if a compatible iOS build exists
  get_ios_build:
    name: Check iOS Build
    needs: [read_app_version]
    type: get-build
    params:
      platform: ios
      profile: preview
      runtime_version: ${{ needs.read_app_version.outputs.app_version }}
      app_version: ${{ needs.read_app_version.outputs.app_version }}

  # 5. Publish OTA update if build exists
  update_ios:
    name: Publish iOS OTA update
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    type: update
    params:
      platform: ios
      branch: preview
      message: "OTA update for version ${{ needs.read_app_version.outputs.app_version }}"
