name: preview-ota-update

on:
  push:
    branches:
      - develop
      - staging
      - feature/**
      - bugfix/**
    paths:
      - src/**
      - assets/**
      - index.js

jobs:
  # 1. Read App Version
  read_app_version:
    name: read-app-version
    type: custom
    env:
      EXPO_DEBUG: "1"
    steps:
      - uses: eas/checkout
      - id: read
        run: |
          VER=$(node -p "require('./package.json').version")
          set-output app_version "$VER"
    outputs:
      app_version: ${{ steps.read.outputs.app_version }}

  # 2. Check if a compatible Android build exists
  get_android_build:
    name: check-android-build
    needs: [read_app_version]
    type: get-build
    params:
      platform: android
      profile: preview
      runtime_version: ${{ needs.read_app_version.outputs.app_version }}
      app_version: ${{ needs.read_app_version.outputs.app_version }}

  # 3. Publish OTA update if build exists
  update_android:
    name: publish-ota-android-update
    needs: [get_android_build]
    if: ${{ needs.get_android_build.outputs.build_id }}
    type: update
    env:
      EXPO_DEBUG: "1"
    params:
      platform: android
      branch: preview
      message: "OTA update for version ${{ needs.read_app_version.outputs.app_version }}"

  # 4. Check if a compatible iOS build exists
  get_ios_build:
    name: check-ios-build
    needs: [read_app_version]
    type: get-build
    params:
      platform: ios
      profile: preview
      runtime_version: ${{ needs.read_app_version.outputs.app_version }}
      app_version: ${{ needs.read_app_version.outputs.app_version }}

  # 5. Publish OTA update if build exists
  update_ios:
    name: publish-ota-ios-update
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    type: update
    env:
      EXPO_DEBUG: "1"
    params:
      platform: ios
      branch: preview
      message: "OTA update for version ${{ needs.read_app_version.outputs.app_version }}"
